import {
  Menu,
  BarChart3,
  Edit3,
  MessageSquare,
  UserRoundPen,
  ClipboardPenLine,
  MailCheck,
  ArrowLeft,
  KeyRound,
  CheckCircle,
  LoaderCircle,
  AlertCircle,
  Lightbulb,
  Settings,
  Gauge,
  Users,
  LogOut,
  UserCircle,
  Undo2,
  UserPlus,
  Search,
  EllipsisVerticalIcon,
  FileText,
  ClipboardList,
  Pencil,
  Trash2,
  CalendarDays,
  CalendarPlus,
  List,
} from 'lucide-react';

import { FaXTwitter, FaGithub } from 'react-icons/fa6';
import { FaRunning, FaRegCommentDots } from 'react-icons/fa';
import { PiShootingStar } from 'react-icons/pi';
import { FcGoogle } from 'react-icons/fc';

export const Icons = {
  Menu,
  BarChart3,
  Edit3,
  MessageSquare,
  UserRoundPen,
  ClipboardPenLine,
  MailCheck,
  ArrowLeft,
  KeyRound,
  CheckCircle,
  LoaderCircle,
  AlertCircle,
  Lightbulb,
  Settings,
  Gauge,
  Users,
  LogOut,
  UserCircle,
  Undo2,
  UserPlus,
  Search,
  EllipsisVerticalIcon,
  FileText,
  ClipboardList,
  Pencil,
  Trash2,
  CalendarDays,
  CalendarPlus,
  List,
  FaXTwitter,
  FaGithub,
  FcGoogle,
  FaRunning,
  FaRegCommentDots,
  PiShootingStar,
};
